use_frameworks!

platform :ios, '8.0'

target 'FakeBaiduTTS_Example' do
  pod 'FakeBaiduTTS', :path => '../'

  target 'FakeBaiduTTS_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
